BS-18: Add Regular Staking, Unstaking & Claim
Rock-n-Block/bitgear-frontend pull request #51
Opened 2022-05-25 13:11 UTC by Kamikozz

https://manzoni.atlassian.net/browse/BS-18

* refactor walletConnect to fetch data without having logged in

* feat add Stake, Unstake & Claim Logic for regular (master) contract (PID = 0) [0xbe5ef7839132CEc790bEC588aEB74478DdAc7990]

// NOTE: without fetching USD
// NOTE: without APR, APY

2022-05-31 13:06 UTC, ValnetineKul requested changes

2022-05-31 13:06 UTC, ValnetineKul commented on src/pages/PageStake/components/Stake/Stake.tsx
> +          {(() => {
Если ни чем, то убери везде

2022-05-31 13:06 UTC, ValnetineKul commented on src/pages/PageStake/components/Stake/Stake.tsx
> +                    classNameCustom={styles.stakeUnstakeButton}
создай вверху useMemo buttonState, которая вернет тебе колбек и текст в кнопке и почикай вот это

2022-05-31 18:59 UTC, Kamikozz commented on src/pages/PageStake/components/SectionHead/index.tsx
> +          // eslint-disable-next-line prettier/prettier
Та тут преттиер конфликтует с еслинтом за то где должны скобки располагаться. Если отключить целиком преттиер в итоге не будет форматтера)
пытался нагуглить решение, не понял в чем трабл

2022-05-31 19:02 UTC, Kamikozz commented on src/pages/PageStake/components/Stake/Stake.tsx
> +  const validateAndChangeInputValue = useCallback(
Нужны, потому что прокидываются внутрь компонентов через проп onClick

2022-05-31 19:03 UTC, Kamikozz commented on src/hooks/useRefresh.tsx
> +    const interval = setInterval(async () => {
Скопировал хук с рефайнери без рефакторинга) fixed

2022-05-31 19:12 UTC, Kamikozz commented on src/pages/PageStake/components/Reward/index.tsx
> +  const isDisabledSubmitButton = useMemo(() => {
Тут вроде я по-быстрому закоммитил работу для дальнейшей проработки состояний, чтобы не пришлось переписывать готовую конструкцию.

fixed

2022-05-31 19:17 UTC, Kamikozz commented on src/pages/PageStake/components/NoConnectWalletPlaceholder/NoConnectWalletPlaceholder.module.scss
> +  color: #fff;
заменил на $color-text-primary

2022-05-31 19:32 UTC, Kamikozz commented on src/hooks/store/staking/regular/useStakingRegular.ts
> +  useEffect(() => {
Наверное, тогда будет неправильно работать, поскольку массив зависимостей будет общим и любое изменение состояния любого запроса будет дергать эффект и невозможно будет написать условие которое корректно бы запускало рефетч
1 вариант (пока все фетчи не станут саксесс не произойдет рефетч)
```ts
  useEffect(() => {
    if (
      stakeRequestStatus !== RequestStatus.SUCCESS &&
      unstakeRequestStatus !== RequestStatus.SUCCESS
    )
      return;
    refetchData();
  }, [refetchData, stakeRequestStatus, unstakeRequestStatus]);
  ```
  
  2 вариант (будет рефетчить данные, например, в случае если 1 запрос SUCCESS, а другой REQUEST, ERROR)
```ts
  useEffect(() => {
    if (
      stakeRequestStatus === RequestStatus.SUCCESS ||
      unstakeRequestStatus === RequestStatus.SUCCESS
    ) {
         refetchData();
    }
  }, [refetchData, stakeRequestStatus, unstakeRequestStatus]);
  ```
  
  3 вариант:
  if (cond1) {
     return refetchData();
   }
   
   if (cond2) {
     return refetchData();
   }
   
   по-моему в таком случае лучше 3 отдельных эффекта завести (код не уменьшится, только лишний раз будет коллбек дергаться при изменениях не связанных с ним

2022-06-01 06:50 UTC, ValnetineKul commented on src/hooks/store/staking/regular/useStakingRegular.ts
> +  useEffect(() => {
3ий вариант
useEffect(() => {
    if ( stakeRequestStatus !== RequestStatus.SUCCESS) {
      return;
    }
      if (unstakeRequestStatus !== RequestStatus.SUCCESS){
      return;
     {
         refetchData();
    }
  }, [refetchData, stakeRequestStatus, unstakeRequestStatus]);

2022-06-01 06:50 UTC, ValnetineKul commented on src/hooks/store/staking/regular/useStakingRegular.ts
> +  useEffect(() => {
Все то же самое в 1 еффекте

2022-06-09 20:46 UTC, Kamikozz commented on src/pages/PageStake/components/Stake/Stake.tsx
> +          {(() => {
fixed in 5ed565d

2022-06-09 20:47 UTC, merged