BS-26: Add swap platform fees
Rock-n-Block/bitgear-frontend pull request #55
Opened 2022-05-30 23:29 UTC by Kamikozz

https://manzoni.atlassian.net/browse/BS-26

2022-06-02 08:19 UTC, ValnetineKul requested changes

2022-06-02 08:19 UTC, ValnetineKul commented on src/components/ModalContentQuotes/index.tsx
>    onClose = () => {},
Вообще в таких местах лучше юзать noop из lodash, часто линтеры настраивают чтобы запретить пустые функции

2022-06-02 08:19 UTC, ValnetineKul commented on src/components/ModalContentQuotes/index.tsx
>        console.log('ModalContentQuotes getQuote:', resultGetQuote);
не твое, но удали

2022-06-02 08:19 UTC, ValnetineKul commented on src/pages/PageMarkets/PageMarketsContent/index.tsx
> +      console.log('trade props:', tradeProps);
удали

2022-06-16 11:35 UTC, Kamikozz commented on src/components/ModalContentQuotes/index.tsx
>        console.log('ModalContentQuotes getQuote:', resultGetQuote);
removed comments in 9f78c14

2022-06-16 11:35 UTC, Kamikozz commented on src/pages/PageMarkets/PageMarketsContent/index.tsx
> +      console.log('trade props:', tradeProps);
removed comments in 9f78c14

2022-06-16 11:36 UTC, merged